#!/bin/sh

# The automake and autoconf commands which need to be run

aclocal

autoheader -I joe

automake -a -c

automake -a -c man/Makefile

automake -a -c joe/Makefile

automake -a -c man/ru/Makefile

automake -a -c rc/Makefile

automake -a -c syntax/Makefile

automake -a -c po/Makefile

autoconf
