#!/bin/bash

# Do cygwin build

# this creates: joe-3.6-1.tar.bz2 and joe-3.6-1-src.tar.bz2
# you also need setup.hint

JOEVERSION=3.7
CYGVERSION=3.7-1

./autojoe

# Force use of /etc/termcap file because Cygwin's tgoto() is broken

# Install aspell first!

./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --libexecdir=/usr/sbin \
  --localstatedir=/var \
  --datadir=/usr/share \
  --mandir=/usr/share/man \
  --infodir=/usr/share/info \
  --docdir=/usr/share/doc/joe-${JOEVERSION} \
  --disable-curses \
  --disable-termcap

make clean

make

make install

(cd /; tar cf - etc/joe usr/share/joe usr/share/doc/joe-${JOEVERSION} \
usr/bin/joe.exe usr/bin/jmacs usr/bin/jstar \
usr/bin/jpico usr/bin/rjoe `cd /; \
find usr/share/man -name 'joe.1'`) | bzip2 >joe-$CYGVERSION.tar.bz2

make dist

gunzip <joe-$JOEVERSION.tar.gz | bzip2 >joe-$CYGVERSION-src.tar.bz2
